### ISSUE TITLE
developing the desktop app with electron and making this app fancy!

### ISSUE THREAD

**Issue by Nima-Ra** [samanthaming/not-fancy-vue-todo#1]
Hi
I think this is a good idea to make a electron app for this todo manager!
So we can set notifications, alarms, widgets and ...
Whats your idea?!

**Comment by samanthaming** [comment]
That is a good idea! I haven't looked into electron yet. But don't let that stop you. Feel free to iterate and build it! That will be your "fancy app challenge" :P 👍

**Comment by Nima-Ra** [comment]
Oh thanks! I'll share the results with you!!
